### ISSUE TITLE
Accidents Happen

### ISSUE THREAD

**Issue by Naendo** [Naendo/twitch-net#1]
@ThindalTV hey i accidently declined your friend request on discord. Please request again or write me your concerns under this ticket.

**Comment by ThindalTV** [comment]
Hi Naendo.

I was mostly just wondering if you were accepting unsolicited PRs on this project. I've got a couple of ideas on how to make it a bit more general in how it works. You'd be 100% free to deny them of course, just wondering if you'd consider them at all.

Best regards,
Thindal

**Comment by Naendo** [comment]
Hey,

I'm happy to receive any sort of feedback on the project!
Feel free to create as many PR as you want. There now is beta documentation btw! 
https://naendo.github.io/twitch-net/

Best regards,
Naendo
